import { chromium } from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1448,height:1086}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/');await page.waitForSelector('[data-testid=postcard]');await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(750);await page.screenshot({path:'tests/desktop.png',fullPage:true});
const assert=(value,message)=>{if(!value)throw new Error(message)};
assert(await page.getByTestId('postcard').count()===18,'18 active cards');await page.getByRole('textbox',{name:'Tìm bài hát'}).fill('nang qua');assert(await page.getByTestId('postcard').count()===1,'accent search');await page.getByTestId('postcard').click();await page.getByRole('button',{name:'Yêu thích kỷ niệm',exact:true}).click();assert(await page.getByRole('button',{name:'Yêu thích kỷ niệm',exact:true}).getAttribute('aria-pressed')==='true','favorite');await page.getByRole('button',{name:'Đóng',exact:true}).click();await page.getByRole('textbox',{name:'Tìm bài hát'}).fill('');await page.getByRole('combobox',{name:'Sắp xếp thư viện'}).selectOption('popular');assert(await page.getByTestId('postcard').count()===6,'popularity only songs');await page.getByRole('combobox',{name:'Sắp xếp thư viện'}).selectOption('latest');const before=await page.getByTestId('postcard').first().getAttribute('style');await page.getByRole('button',{name:'Xáo rổ ảnh'}).click();await page.waitForTimeout(700);assert(before!==await page.getByTestId('postcard').first().getAttribute('style'),'shuffle layout');
await page.getByRole('button',{name:'Tải lên'}).click();await page.getByRole('button',{name:'Thử giao diện quản lý'}).click();await page.getByLabel('Tên / tiêu đề').fill('Kiểm thử âm thanh');
const seconds=3,rate=8000,n=rate*seconds;const wav=Buffer.alloc(44+n*2);wav.write('RIFF');wav.writeUInt32LE(36+n*2,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)wav.writeInt16LE(Math.round(Math.sin(i/rate*440*Math.PI*2)*800),44+i*2);
await page.getByLabel('Âm thanh · tối đa 24 MB').setInputFiles({name:'test.wav',mimeType:'audio/wav',buffer:wav});await page.getByLabel('Ảnh bìa · tối đa 8 MB').setInputFiles('public/images/coast.jpg');await page.getByRole('button',{name:'Thêm kỷ niệm'}).click();await page.getByText('Đã thêm vào rổ kỷ niệm.').waitFor();await page.getByRole('button',{name:'Đóng',exact:true}).click();await page.getByRole('button',{name:'Nghe bài mới nhất'}).click();await page.waitForTimeout(500);assert(await page.locator('audio').evaluate(a=>!a.paused),'audio playing');await page.getByRole('button',{name:'Đóng',exact:true}).click();assert(await page.locator('audio').evaluate(a=>!a.paused),'close preserves playback');await page.getByRole('switch',{name:'Giao diện đêm'}).click();assert(await page.locator('audio').evaluate(a=>!a.paused),'theme switch preserves playback');await page.getByRole('button',{name:'Tạm dừng',exact:true}).click();assert(await page.locator('audio').evaluate(a=>a.paused),'pause');await page.getByRole('slider',{name:'Vị trí phát'}).fill('1.5');await page.waitForTimeout(200); console.log('seek position',await page.locator('audio').evaluate(a=>a.currentTime)); assert(await page.locator('audio').evaluate(a=>a.currentTime)>1,'seek');await page.getByRole('button',{name:'Bài tiếp'}).click();await page.getByRole('button',{name:'Đóng',exact:true}).click();
await page.getByRole('textbox',{name:'Tìm bài hát'}).fill('nang qua');const card=page.getByTestId('postcard');const bounds=await card.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2+55,bounds.y+bounds.height/2+30,{steps:10});await page.mouse.up();await page.waitForTimeout(150);assert(await page.locator('dialog').count()===0,'drag does not click');const moved=await card.boundingBox();assert(Math.abs(moved.x-bounds.x)>10,'card moves');await card.focus();await page.keyboard.press('Enter');await page.locator('dialog').waitFor();await page.keyboard.press('Escape');assert(await page.locator('dialog').count()===0,'keyboard close');await page.getByRole('textbox',{name:'Tìm bài hát'}).fill('');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile no overflow');assert(errors.length===0,errors.join('\n'));await browser.close();fs.writeFileSync('tests/browser-results.json',JSON.stringify({passed:true,checks:['initial 18 cards','accent search','selection','favorite','popular filter','shuffle','demo owner sign-in','demo upload','real audio play/pause','seek','next','close preserves playback','drag movement','drag suppresses click','keyboard open/Escape','mobile overflow','no page errors'],errors},null,2));console.log('Browser checks passed');




