import {useEffect,useRef,useState} from 'react';
import type {Song} from './types';
export function useAudioPlayer(){const audio=useRef<HTMLAudioElement>(null);const [track,setTrack]=useState<Song>();const [playing,setPlaying]=useState(false);const [elapsed,setElapsed]=useState(0);const [duration,setDuration]=useState(0);const [volume,setVolume]=useState(.75);const [muted,setMuted]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [repeat,setRepeat]=useState(false);const [shuffle,setShuffle]=useState(false);const pending=useRef(false);
 const play=async()=>{if(!audio.current||!track?.audioUrl){setError('Bản thu chưa được thêm. Vui lòng chọn bài khác hoặc tải lên bản thu khi có quyền quản lý.');return}try{setError('');await audio.current.play()}catch{setLoading(false);setError('Chưa thể phát. Hãy nhấn phát lại hoặc kiểm tra tệp âm thanh.')}};
 const select=(song:Song,autoplay=false)=>{setError(song.audioUrl?'':'Bản thu chưa được thêm.');if(track?.id===song.id){if(autoplay)void play();return}pending.current=autoplay;setPlaying(false);setElapsed(0);setDuration(0);setTrack(song)};
 useEffect(()=>{if(!audio.current)return;audio.current.load();if(track?.audioUrl&&pending.current){pending.current=false;void play()}},[track?.id]);
 useEffect(()=>{if(audio.current){audio.current.volume=volume;audio.current.muted=muted}},[volume,muted]);
 return {audio,track,playing,elapsed,duration,volume,muted,error,loading,repeat,shuffle,select,play,toggle:()=>playing?audio.current?.pause():void play(),setVolume,setMuted,setRepeat,setShuffle,seek:(n:number)=>{if(audio.current&&Number.isFinite(audio.current.duration))audio.current.currentTime=n},events:{onPlay:()=>setPlaying(true),onPause:()=>setPlaying(false),onTimeUpdate:()=>setElapsed(audio.current?.currentTime||0),onLoadedMetadata:()=>setDuration(audio.current?.duration||0),onWaiting:()=>setLoading(true),onCanPlay:()=>setLoading(false),onError:()=>{setPlaying(false);setLoading(false);setError('Không thể đọc tệp âm thanh. Vui lòng kiểm tra định dạng hoặc thử lại.')}}};}

